login:
    path: /
    controller: App\Controller\UserController::login

# Para el logout no hace falta hacer una acción porque ya se encarga symfony de hacerlo automaticamente 
logout:
    path: /logout

tasks:
    path: /tareas
    controller: App\Controller\TaskController::index
    
task_detail:
    path: /tarea/{id}
    controller: App\Controller\TaskController::detail
    
task_create:
    path: /crear-tarea
    controller: App\Controller\TaskController::createTask
    
my_tasks:
    path: /mis-tareas
    controller: App\Controller\TaskController::myTasks
    
task_edit:
    path: /editar-tarea/{id}
    controller: App\Controller\TaskController::edit
    
task_delete:
    path: /borrar-tarea/{id}
    controller: App\Controller\TaskController::delete
    
register:
    path: /registro
    controller: App\Controller\UserController::register