#index: // aquí especificamos el nombre que va a tener la ruta. Esto es útil a la hora de usarlo luego en enlaces, redirecciones, etc
#    path: /inicio  // aquí definimos la ruta (por ejemplo /user/create o /image/delete)
#    controller: App\Controller\HomeController::index  // aquí especificamos el controlador y la acción a la que está asociada esta ruta
index:  
    path: /inicio
    controller: App\Controller\HomeController::index

# Para pasar parámetros por la url lo hacemos como en laravel dentro del apartado path: 
# Entre llaves ({param}) si queremos que sea obligatorio o con un interrogante ({param?}) si queremos que sea opcional 
# Podemos definir un defaults: { param: 'valor' } para darle un valor a ese parámetro por defecto
# Los parámetros deberán ser recogidos como parámetros en el método
# También podemos definir el método http que usará esa ruta con una etiqueta methods que recibirá un array con los métodos
# También podemos definir expresiones regulares para validar los parámetros que me llegan por la url con el requirements
animales:  
    path: /animales/{nombre}/{edad?}
    controller: App\Controller\HomeController::animales
    defaults: { nombre: 'Víctor', edad: 30 }
    methods: [GET]
    requirements:
        nombre: '[a-zA-Z]+'
        edad: '[0-9]+'

redirigir:  
    path: /redirigir
    controller: App\Controller\HomeController::redirigir
    
animal_index:  
    path: /animal/index
    controller: App\Controller\AnimalController::index
    
animal_save:  
    path: /animal/save
    controller: App\Controller\AnimalController::save
    
animal_detail:  
    path: /animal/detail/{id}
    controller: App\Controller\AnimalController::animal
    
animal_update:  
    path: /animal/update/{id}
    controller: App\Controller\AnimalController::update
    
animal_delete:  
    path: /animal/delete/{id}
    controller: App\Controller\AnimalController::delete
    
animal_create:  
    path: /crear-animal
    controller: App\Controller\AnimalController::crearAnimal
    
email_validate:  
    path: /validar-email/{email}
    controller: App\Controller\AnimalController::validarEmail